# Generated by Django 4.2.7 on 2025-12-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listingimage",
            name="image",
            field=models.TextField(),
        ),
    ]
