# Generated by Django 4.2.7 on 2025-12-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_change_image_to_textfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("like_new", "Like New"),
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                ],
                default="good",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
